services:
  bot-buyer:
    build:
      context: ./
    container_name: buyer
    volumes:
      - logs_buyer:/app
    environment:
      DONOR: 1111111111111
      RECIPIENT: 2222222222222
      FILESESSION: "name"
    command: python3 main.py
    restart: always
  
volumes:
  logs_buyer:
